const fs = require('fs');
const si = require('simple-icons');

const map = {
  openai: 'siOpenai',
  claude: 'siAnthropic',
  gemini: 'siGooglegemini',
  ollama: 'siOllama',
  huggingface: 'siHuggingface',
  mistral: 'siMistral',
  cohere: 'siCohere',
  pinecone: 'siPinecone',
  qdrant: 'siQdrant',
  milvus: 'siMilvus',
  elevenlabs: 'siElevenlabs',
  midjourney: 'siMidjourney',
  dalle: 'siOpenai',
  stablediffusion: 'siStability',
  replicate: 'siReplicate',
  aws_textract: 'siAmazonaws',
  google_vision: 'siGooglecloud',
  instagram: 'siInstagram',
  facebook: 'siFacebook',
  twitter: 'siX',
  linkedin: 'siLinkedin',
  tiktok: 'siTiktok',
  pinterest: 'siPinterest',
  youtube: 'siYoutube',
  reddit: 'siReddit',
  discord: 'siDiscord',
  snapchat: 'siSnapchat',
  telegram: 'siTelegram',
  whatsapp: 'siWhatsapp',
  slack: 'siSlack',
  twitch: 'siTwitch',
  gmail: 'siGmail',
  outlook: 'siMicrosoftoutlook',
  sendgrid: 'siSendgrid',
  mailchimp: 'siMailchimp',
  twilio: 'siTwilio',
  postmark: 'siPostmark',
  activecampaign: 'siActivecampaign',
  customerio: 'siCustomerio',
  klaviyo: 'siKlaviyo',
  intercom: 'siIntercom',
  zendesk: 'siZendesk',
  freshdesk: 'siFreshdesk',
  mysql: 'siMysql',
  postgresql: 'siPostgresql',
  mongodb: 'siMongodb',
  redis: 'siRedis',
  supabase: 'siSupabase',
  firebase: 'siFirebase',
  snowflake: 'siSnowflake',
  bigquery: 'siGooglebigquery',
  aws_s3: 'siAmazons3',
  airtable: 'siAirtable',
  notion: 'siNotion',
  google_sheets: 'siGooglesheets',
  excel: 'siMicrosoftexcel',
  dynamodb: 'siAmazondynamodb',
  elasticsearch: 'siElasticsearch',
  salesforce: 'siSalesforce',
  hubspot: 'siHubspot',
  pipedrive: 'siPipedrive',
  zoho: 'siZoho',
  monday: 'siMondaydotcom',
  clickup: 'siClickup',
  asana: 'siAsana',
  trello: 'siTrello',
  jira: 'siJira',
  linear: 'siLinear',
  stripe: 'siStripe',
  paypal: 'siPaypal',
  square: 'siSquare',
  shopify: 'siShopify',
  woocommerce: 'siWoocommerce',
  google_analytics: 'siGoogleanalytics',
  mixpanel: 'siMixpanel',
  amplitude: 'siAmplitude',
  segment: 'siSegment',
  facebook_ads: 'siFacebook',
  google_ads: 'siGoogleads',
  linkedin_ads: 'siLinkedin',
  tiktok_ads: 'siTiktok',
  hotjar: 'siHotjar',
  mailgun: 'siMailgun',
  typeform: 'siTypeform',
  typebot: 'siTypebot',
  github: 'siGithub',
  gitlab: 'siGitlab',
  bitbucket: 'siBitbucket',
  docker: 'siDocker',
  aws_ec2: 'siAmazonec2',
  vercel: 'siVercel',
  netlify: 'siNetlify',
  cloudflare: 'siCloudflare',
  datadog: 'siDatadog',
  sentry: 'siSentry',
  pagerduty: 'siPagerduty',
  grafana: 'siGrafana'
};

let out = 'export const BRAND_SVGS: Record<string, string> = {\n';
for (const [k, v] of Object.entries(map)) {
  if (si[v]) {
    out += `  '${k}': '${si[v].path}',\n`;
  }
}
out += '};\n';
fs.writeFileSync('src/brandIcons.ts', out);
