import React from "react";
import { Link } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import "../styles/legal.css";

const LAST_UPDATED = "May 2026";
const CONTACT_EMAIL = "legal@ropeli.ai";
const COMPANY_NAME = "Ropeli";

export default function Terms() {
  return (
    <>
      <Navbar />
      <div className="legal-page">
        <div className="legal-container">
          <Link to="/" className="legal-back">
            ← Back to Ropeli
          </Link>

          <h1>Terms of Service</h1>
          <p className="legal-updated">Last updated: {LAST_UPDATED}</p>

          <section>
            <h2>1. Acceptance</h2>
            <p>
              By creating an account or using {COMPANY_NAME}, you agree to these Terms. If you do
              not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2>2. The Service</h2>
            <p>
              {COMPANY_NAME} is an AI-powered tool that generates React Native mobile app source
              code from plain-English descriptions. The service includes a web-based builder, mobile
              preview via Expo Go, and optional APK builds via Expo Application Services.
            </p>
          </section>

          <section>
            <h2>3. Who Owns the Generated Code</h2>
            <p>
              <strong>You own it.</strong> All source code generated by {COMPANY_NAME} in response
              to your prompts is yours. You may use it for any purpose — personal, commercial, open
              source, or proprietary — without restriction or royalty. {COMPANY_NAME} makes no
              claim to ownership of generated code.
            </p>
            <p>
              Note: The AI models used to generate code are trained on publicly available code. We
              cannot guarantee that generated code is free of third-party IP claims. Review
              generated code before commercial use.
            </p>
          </section>

          <section>
            <h2>4. Acceptable Use</h2>
            <p>You agree not to use {COMPANY_NAME} to:</p>
            <ul>
              <li>
                Generate malware, spyware, ransomware, or any software designed to harm users
              </li>
              <li>Build apps that violate applicable laws in your jurisdiction</li>
              <li>
                Attempt to circumvent usage limits through automated requests or multiple accounts
              </li>
              <li>
                Reverse-engineer, scrape, or extract the AI prompts or system instructions
              </li>
              <li>Use the service on behalf of others without their consent</li>
              <li>Generate content that is illegal, hateful, or harmful</li>
            </ul>
            <p>Violation of these rules will result in immediate account termination.</p>
          </section>

          <section>
            <h2>5. Usage Limits</h2>
            <p>
              Free accounts: 2 generations per day. Pro accounts: 50 generations per day. Limits
              reset at midnight UTC. We reserve the right to adjust limits with 7 days notice.
            </p>
          </section>

          <section>
            <h2>6. Payment and Refunds</h2>
            <p>
              Pro subscriptions are billed monthly via Razorpay. Subscriptions auto-renew unless
              cancelled before the renewal date. We offer a 7-day refund on the first Pro
              subscription purchase if you are not satisfied. No refunds after the first 7 days or
              on renewals.
            </p>
          </section>

          <section>
            <h2>7. No Warranty</h2>
            <p>{COMPANY_NAME} is provided &quot;as is&quot;. We do not warrant that:</p>
            <ul>
              <li>Generated code will be bug-free, functional, or fit for a particular purpose</li>
              <li>The service will be uninterrupted or error-free</li>
              <li>Generated apps will be accepted by app stores</li>
            </ul>
            <p>
              Generated code is a starting point — always review and test before deploying to users.
            </p>
          </section>

          <section>
            <h2>8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, {COMPANY_NAME} is not liable for any
              indirect, incidental, or consequential damages arising from your use of the service or
              any generated code. Our total liability is limited to the amount you paid us in the 30
              days prior to the claim.
            </p>
          </section>

          <section>
            <h2>9. Termination</h2>
            <p>
              We may terminate or suspend your account for violation of these Terms, with or without
              notice. You may close your account at any time. On termination, your generated projects
              will be deleted within 30 days.
            </p>
          </section>

          <section>
            <h2>10. Changes</h2>
            <p>
              We may update these Terms. Continued use after changes take effect constitutes
              acceptance. We will notify users of material changes by email at least 7 days in
              advance.
            </p>
          </section>

          <section>
            <h2>11. Governing Law</h2>
            <p>
              These Terms are governed by the laws of India. Disputes will be resolved in the courts
              of India.
            </p>
          </section>

          <section>
            <h2>12. Contact</h2>
            <p>
              For legal questions:{" "}
              <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </>
  );
}
