import React from "react";
import { Link } from "react-router-dom";
import "../styles/terms.css";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

const sections = [
  { id: "introduction", label: "Introduction" },
  { id: "license", label: "License to Use Our Services" },
  { id: "user-accounts", label: "User Accounts and Content" },
  { id: "services-pricing", label: "Services and Pricing" },
  { id: "acceptable-use", label: "Acceptable Use" },
  { id: "data-usage-ai", label: "Data Usage and AI Features" },
  { id: "ip-rights", label: "Intellectual Property Rights" },
  { id: "security-privacy", label: "Security and Privacy" },
  { id: "termination", label: "Term and Termination" },
  { id: "disclaimer", label: "Disclaimer of Warranties" },
  { id: "liability", label: "Limitation of Liability" },
  { id: "indemnification", label: "Indemnification" },
  { id: "miscellaneous", label: "Miscellaneous" },
];

export default function Terms() {
  return (
    <>
    <Navbar />
    <div className="terms-page">
      {/* Header */}
      <header className="terms-header">
        <h1>Ropeli AI Terms of Service</h1>
        <p>Last updated: 20 May 2025</p>

        {/*<Link to="/" className="back-home">
          ← Return to Home
        </Link>*/}
      </header>

      {/* Layout */}
      <div className="terms-layout">
        {/* Sidebar */}
        <aside className="terms-sidebar">
          {sections.map((s) => (
            <a key={s.id} href={`#${s.id}`}>
              {s.label}
            </a>
          ))}
        </aside>

        {/* Content */}
        <main className="terms-content">
          {/* 1 */}
          <section id="introduction">
            <h2>1. Introduction</h2>

            <h3>1.1 Agreement Overview</h3>
            <p>
              These Terms of Service ("Terms") constitute a legal agreement
              between you and Ropeli AI ("we," "our," or "us"). Your use of
              ropeli.ai (the "Site") and related services (collectively,
              "Services") is subject to these Terms.
            </p>

            <ul>
              <li>Acknowledge that you have read and understood these Terms</li>
              <li>Agree to be bound by these Terms</li>
              <li>Agree to our Privacy Policy (available at ropeli.ai/privacy)</li>
              <li>Commit to comply with all applicable laws and regulations</li>
            </ul>

            <p>
              If you do not agree with these Terms, you must not download,
              install, access, or use our Services.
            </p>

            <h3>1.2 Definitions</h3>
            <ul>
              <li><strong>"Site":</strong> our website and associated tools for app development</li>
              <li><strong>"Content":</strong> code, projects, data, files, and other materials created, modified, or accessed via our Services</li>
              <li><strong>"User":</strong> anyone who downloads, installs, accesses, or uses our Services</li>
              <li><strong>"Authorized User":</strong> a user you authorize to access and use the Services on your account</li>
              <li><strong>"Input":</strong> prompts, commands, and instructions you provide</li>
              <li><strong>"Output":</strong> code, responses, and other content generated by the Services</li>
            </ul>
          </section>

          {/* 2 */}
          <section id="license">
            <h2>2. License to Use Our Services</h2>

            <h3>2.1 Rights Granted</h3>
            <p>
              Ropeli AI provides a limited, personal, non-exclusive,
              non-transferable license to use our Services.
            </p>

            <ul>
              <li>Free Plan: Personal, non-commercial use</li>
              <li>Paid Plans: Commercial use per your subscription</li>
            </ul>

            <h3>2.2 Restrictions</h3>
            <ul>
              <li>Distribute, sell, rent, lease, or sublicense our Services</li>
              <li>Remove or alter proprietary notices or labels</li>
              <li>Harm, disable, or impair our systems</li>
              <li>Use automated scripts to collect/interact with our Services</li>
              <li>Use for any illegal purpose or in violation of laws</li>
            </ul>

            <h3>2.3 Reservation of Rights</h3>
            <p>
              All rights not expressly granted are reserved by Ropeli AI. You do
              not acquire ownership rights in our Services.
            </p>
          </section>

          {/* 3 */}
          <section id="user-accounts">
            <h2>3. User Accounts and Content</h2>

            <h3>3.1 Account Creation and Management</h3>
            <ul>
              <li>You may need to create an account</li>
              <li>Provide accurate, current info</li>
              <li>Maintain account confidentiality</li>
              <li>You are responsible for all activities in your account</li>
              <li>Notify us immediately of unauthorized use</li>
            </ul>

            <h3>3.2 Minimum Age</h3>
            <ul>
              <li>You must be an adult to use the Service.</li>
              <li>If younger than 13, parent/guardian consent is required.</li>
            </ul>

            <h3>3.3 Account Deletion</h3>
            <ul>
              <li>Request deletion by contacting support@ropeli.ai</li>
              <li>Your profile and content will be deleted within 90 days</li>
            </ul>

            <h3>3.4 User Content</h3>
            <p>
              You retain ownership of your Content, subject to licenses in these
              Terms.
            </p>

            <h3>3.5 License to User Content</h3>
            <p>
              You grant Ropeli AI a non-exclusive, worldwide, royalty-free
              license to access, use, copy, distribute, perform, export, and
              display your Content as necessary to provide services, address
              technical issues, and comply with legal obligations.
            </p>

            <h3>3.6 Content Backups</h3>
            <p>
              You are responsible for backing up your Content; we don’t
              guarantee against loss/corruption.
            </p>
          </section>

          {/* 4 */}
          <section id="services-pricing">
            <h2>4. Services and Pricing</h2>

            <h3>4.1 Plans and Limits</h3>
            <ul>
              <li>Plans, features, and limits are posted at ropeli.ai/pricing</li>
              <li>Details may change at any time</li>
            </ul>

            <h3>4.2 Subscription and Payment Terms</h3>
            <ul>
              <li>Subscriptions are recurring (monthly or annual)</li>
              <li>Renew automatically unless canceled</li>
              <li>Payments are non-refundable unless stated</li>
              <li>Failed payments may suspend/terminate access</li>
            </ul>

            <h3>4.3 Support</h3>
            <ul>
              <li>Free Plan: Community support</li>
              <li>Paid Plans: Priority email support</li>
              <li>Enterprise: Dedicated SLAs</li>
            </ul>

            <h3>4.4 Service Delivery</h3>
            <ul>
              <li>Access is granted immediately on payment</li>
              <li>Possible maintenance or outages may occur</li>
            </ul>

            <h3>4.5 Refund Policies</h3>
            <ul>
              <li>Payments are non-refundable unless otherwise stated</li>
              <li>Approved refunds processed within 14 days</li>
            </ul>

            <h3>4.6 Cancellation Policy</h3>
            <ul>
              <li>Cancel anytime in account settings</li>
              <li>No partial refunds</li>
              <li>Expired credits are not refunded</li>
            </ul>
          </section>

          {/* 5 */}
          <section id="acceptable-use">
            <h2>5. Acceptable Use</h2>
            <ul>
              <li>No violation of laws</li>
              <li>No infringement of intellectual property</li>
              <li>No harmful code or abuse</li>
              <li>No interfering with systems or users</li>
            </ul>

            <h3>Export Controls</h3>
            <ul>
              <li>Users must comply with export laws</li>
              <li>Restricted users may not use Services</li>
            </ul>
          </section>

          {/* 6 */}
          <section id="data-usage-ai">
            <h2>6. Data Usage and AI Features</h2>
            <ul>
              <li>Usage data analyzed to improve services</li>
              <li>No AI training on proprietary code without consent</li>
              <li>Enterprise protections available</li>
            </ul>
          </section>

          {/* 7 */}
          <section id="ip-rights">
            <h2>7. Intellectual Property Rights</h2>
            <ul>
              <li>Ropeli AI owns platform IP</li>
              <li>You own generated code</li>
              <li>You may modify, sell, or open source generated code</li>
            </ul>
          </section>

          {/* 8 */}
          <section id="security-privacy">
            <h2>8. Security and Privacy</h2>
            <ul>
              <li>Reasonable security measures applied</li>
              <li>Personal data governed by Privacy Policy</li>
              <li>GDPR DPA available on request</li>
            </ul>
          </section>

          {/* 9 */}
          <section id="termination">
            <h2>9. Term and Termination</h2>
            <ul>
              <li>Effective upon first use</li>
              <li>Termination for violations or non-payment</li>
              <li>Content deleted within 90 days</li>
            </ul>
          </section>

          {/* 10 */}
          <section id="disclaimer">
            <h2>10. Disclaimer of Warranties</h2>
            <p>
              Services are provided “as is” and “as available.”
              No guarantees of functionality or reliability.
            </p>
          </section>

          {/* 11 */}
          <section id="liability">
            <h2>11. Limitation of Liability</h2>
            <p>
              Ropeli AI is not liable for indirect, incidental, or consequential
              damages.
            </p>
          </section>

          {/* 12 */}
          <section id="indemnification">
            <h2>12. Indemnification</h2>
            <p>
              You agree to indemnify Ropeli AI against claims arising from your
              use or violation of these Terms.
            </p>
          </section>

          {/* 13 */}
          <section id="miscellaneous">
            <h2>13. Miscellaneous</h2>
            <ul>
              <li>Governing Law: State of California</li>
              <li>Dispute Resolution: Alameda County, California</li>
              <li>Modifications: Continued use indicates acceptance</li>
              <li>Contact: support@ropeli.ai</li>
            </ul>
          </section>
        </main>
      </div>
    </div>
        <Footer />
    </>
  );
}
